### ISSUE TITLE
Landmarks

### ISSUE THREAD

**Issue by Golbstein** [JeffLIrion/python-graphslam#23]
Hi and thanks for this repo!

Is this possible to add landmarks in your implementation?

**Comment by mihany** [comment]
> Hi and thanks for this repo!
> 
> Is this possible to add landmarks in your implementation?

Same here

**Comment by JeffLIrion** [comment]
Some resources:
* https://github.com/RainerKuemmerle/g2o/wiki/File-format-slam-3d
* https://github.com/RainerKuemmerle/g2o/blob/master/g2o/types/slam3d/edge_se3_pointxyz.cpp
* https://github.com/borglab/gtsam/pull/396/files

**Comment by JeffLIrion** [comment]
@Golbstein or @mihany, could you please point me to a .g2o dataset that contains landmark edges.

**Comment by JeffLIrion** [comment]
Here's a start: https://github.com/JeffLIrion/python-graphslam/pull/53

But I need to know if the error function is correct: https://github.com/JeffLIrion/python-graphslam/blob/bbaffb6d149dd8fe98201fb135bbfca336a3dac3/graphslam/edge/edge_landmark.py#L54-L68

**Comment by JeffLIrion** [comment]
Reading and writing `PoseR2` and `PoseR3` vertices in .g2o files is supported: [Support VERTEX_XY and VERTEX_TRACKXYZ vertices in .g2o files](https://github.com/JeffLIrion/python-graphslam/pull/47)

Reading and writing `EDGE_SE2_XY` and `EDGE_SE3_TRACKXYZ` edges in .g2o files is not yet supported. 
* https://docs.ros.org/en/noetic/api/rtabmap/html/OptimizerG2O_8cpp_source.html

Calculating error for landmark edges is implemented in https://github.com/JeffLIrion/python-graphslam/pull/53, but I don't know if it's the same calculation as in g2o.

**Comment by JeffLIrion** [comment]
I looked at the g2o code and used the same error function that they have. The pull request is almost done. The main thing left is to fully support reading and writing the edges in the .g2o format. Specifically, the offset is not yet supported. I haven't seen any official documentation for it. 

```
PARAMS_SE3OFFSET 0 0 0 0 0 0 0 1 
...
EDGE_SE3_TRACKXYZ 2 7 0 ...
```

I suppose that in this example, I would store the _SE(3)_ offset from the first line with an ID of 0. And later when loading that edge, since it's an _SE(3)_ landmark edge, I would look for the _SE(3)_ offset with an ID of 0. And likewise for _SE(2)_ offsets and landmark edges. 

It would be good to have a dataset that I could use to validate the pull request before merging it.

**Comment by JeffLIrion** [comment]
This is done!
